# alias|hostname|username

server|server.nexgenads.space|home|
jenkins|server.nexgenads.space|home|jenkins
grafana|server.nexgenads.space|home|grafana
prometheus|server.nexgenads.space|home|prometheus
